### ISSUE TITLE
seem in complete the folder.. where is the sprite / icon ?  

### ISSUE THREAD

**Issue by alien3d** [mervick/emojionearea#1]
icon not included. sprite css also.. i prefer not to link to cdn everytime.

**Comment by mervick** [comment]
This plugin requires [emojione](https://github.com/Ranks/emojione), so you must include `emojione/lib/emojione.min.js` and `emojione/assets/sprites/emojione.sprite.css` in your HTML.
If you include these files from CDN, the image/sprites will use CDN, too.
You can download the `emojione` and include it from your own host.
If you want to use images instead of the sprite,  you don't need to include `sprite.css`, but must set the path to the images, like this:
```js
$(document).ready(function() {
	emojione.imagePathPNG = 'basedir/to/emojione/assets/png/';
});
```

**Comment by alien3d** [comment]
thanks for info..

**Comment by mervick** [comment]
I think I understand what you mean.
From `v1.0.1` you will not need to load emojione, only emojioneArea.

**Comment by kamov** [comment]
I see that you are still using emojione.js on your demo, but this is not anymore required right?
only this two files:
<link rel="stylesheet" href="file/to/path/css/emojionearea.min.css">
<script type="text/javascript" src="file/to/path/js/emojionearea.min.js"></script>

and optionally emojione.sprite.css if sprite image is used?

Thanks

**Comment by glui2001** [comment]
Can not having dependency on CDN be the default configuration?  Or at least expose an option in emojioneArea to switch between emojione CDN and local hosting?

**Comment by mervick** [comment]
For turn off CDN of emojione, (ref https://github.com/mervick/emojionearea/issues/80)
```
jQuery(document).ready(function() {
    emojione.imagePathPNG = 'wherever/you/want/assets/png/';
    emojione.imagePathSVG = 'wherever/you/want/assets/svg/';
    $("#example1").emojioneArea(
        {
            useInternalCDN: false
        }
    );
});
```
