### ISSUE TITLE
Integration with EmojiOne 3.1

### ISSUE THREAD

**Issue by melalj** [mervick/emojionearea#168]
Is it possible to get the integration with the last version fo EmojiOne: https://www.emojione.com/emoji/v3

Thanks,

**Comment by lasdeparq** [comment]
@melalj , Its already integrated in master branch. But it was not update at the npm.
If you need use through npm you can use git url in dependencies (ref https://stackoverflow.com/questions/23338393/npm-install-not-installing-latest-version-on-github)

**Comment by melalj** [comment]
I'm using the CDN `https://cdnjs.cloudflare.com/ajax/libs/emojionearea/3.1.8/emojionearea.js` and still getting the old version of emojis

**Comment by lasdeparq** [comment]
Release 3.1.8 doesn't have support to emojione 3 yet. The version in cdnjs.cloudflare has not been updated yet.  For now you must use the master github version to use emojionearea with support to emojione 3.

@mervick , do you have a prevision to update a version in cdn and npm?

**Comment by mervick** [comment]
@lasdeparq I sent invite to you, please accept it and build the latest release of EmojioneArea and what you think need to do.
Thank you

**Comment by lasdeparq** [comment]
Thank you, @mervick.

**Comment by johnsenpeder** [comment]
@mervick it looks like when using EmojiOne 3.1.1 not all emoji's show up in the picker (Most flags are missing):
![https://i.imgur.com/CXYtmp4.png?1](https://i.imgur.com/CXYtmp4.png?1)

Nor do they all render in the text field:
![https://i.imgur.com/bBgyeX1.png?1](https://i.imgur.com/bBgyeX1.png?1)

**Comment by lasdeparq** [comment]
@melalj , it's now available version 3.2.0 at the `https://cdnjs.cloudflare.com/ajax/libs/emojionearea/3.2.0/emojionearea.js`

**Comment by lasdeparq** [comment]
@johnsenpeder , you can customize the emojis that will appear. This issue that you talk about happens because in emojione 3 the shortname of some emojis changed. Almost all flags shortnames have `flag_` as prefix. We don't change the default config because it would broken compatibility with previous versions of emojione.

I think we need to open another issue to treat a different default configs for emojione 3.

For now you can override the default config as [this fiddle ](https://jsfiddle.net/lasdeparq/aw0o2thq/2/)

**Comment by lasdeparq** [comment]
This problem with emojis and flags have to be treated in the issue #169
