### ISSUE TITLE
EmojiOne attribution link

### ISSUE THREAD

**Issue by pederjohnsen** [mervick/emojionearea#228]
Since EmojiOne (at least version 3) requires an attribution link if using the free version, could it be an idea to add an option to render an attribution link in the footer of the emoji picker?

**Comment by mervick** [comment]
Can you please share reference to this requirements?

**Comment by carpii** [comment]
Its here  https://www.emojione.com/licenses/free#attribution

**Comment by mervick** [comment]
I suggest returning to using the older version of EmojiOne by default.
All who wants to use new EmojiOne will decide by himself where to put links to EmojiOne.
Putting the link into EmojioneArea will not resolve the license issue, because
it require putting this link at the bottom of page or in the place where emojis uses,
so all rendered emojis in the post/comment/etc will require link too.

**Comment by carpii** [comment]
I think even 2.2.7 required attribution for free license holders... 

https://github.com/emojione/emojione/tree/2.2.7

**Comment by carpii** [comment]
Closing this issue as its not practical to add to EmojioneArea picker (and also wouldnt satisfy license requirements anyway)
